export default {
  //CREATE_ACA: "CREATE_COURSE",
  //UPDATE_COURSE: "UPDATE_COURSE",
  //DELETE_COURSE: "DELETE_COURSE",
  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  CREATE_ACA: "CREATE_ACA",
  LOAD_ACCOUNTS:"LOAD_ACCOUNTS",
  LOAD_ACAS: "LOAD_ACAS",
  CREATE_CUSTOMER: "CREATE_CUSTOMER",
  LOAD_TRANSACTIONS: "LOAD_TRANSACTIONS",
  LOAD_CUSTOMERS: "LOAD_CUSTOMERS",
  LOAD_ACCOUNT_TYPES: "LOAD_ACCOUNT_TYPES",
  LOAD_DETAILED_ACCOUNT_DETAILS: "LOAD_DETAILED_ACCOUNT_DETAILS"
};
